### ISSUE TITLE
Error: Exception thrown when you type in invalid user name with out create 

### ISSUE THREAD

**Issue by tsviet** [Agile410/FTPizza#103]
An unhandled exception of type 'System.IndexOutOfRangeException' occurred in FTPizza.exe
![error](https://cloud.githubusercontent.com/assets/13110596/17491848/2f9b16da-5d5e-11e6-8cb5-825a288a17b3.png)

**Comment by tsviet** [comment]
I will work on this one

**Comment by kevbui** [comment]
There is some serious technical debt within ConnectionManager.cs, I'm giving up on reading this class.

**Comment by kevbui** [comment]
Fixed in 4ef2a9e3381c1e00aa74a504da34e32037297fcf
